name:                os-lang
version:             0.1.0.0
license:             GPL-3

dependencies:
- base >= 4.7 && < 5
- lens
- containers
- mtl
- parsec
- text
- recursion-schemes

default-extensions:
- TemplateHaskell
- ViewPatterns
- FlexibleContexts
- ConstraintKinds
- OverloadedStrings
- KindSignatures
- TypeFamilies
- DeriveFunctor
- DeriveFoldable
- DeriveTraversable
- LambdaCase
- ScopedTypeVariables

library:
  source-dirs: src

tests:
  test-lisp:
    source-dirs: test-lisp
    main: TestLisp.hs
    dependencies: os-lang
