((lambda (let1)
   (let1 Z (lambda (f)
             ((lambda (g)
                (f (g g)))
              (lambda (g)
                (f (lambda (x) ((g g) x))))))
         ((Z (lambda (last)
               (lambda (x)
                 (if (cdr x)
                     (last (cdr x))
                   x))))
          '(fi fi fo fum))))
 (mac (name val body)
      (cons (cons 'lambda (cons (cons name '()) (cons body '()))) (cons val '()))))
